default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sw-portfolio_development
  user: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']

test:
  <<: *default
  database: sw-portfolio_test

production:
  <<: *default
  database: sw-portfolio_production
