default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sw-portfolio_development
  user:
  password:

test:
  <<: *default
  database: sw-portfolio_test

production:
  <<: *default
  database: sw-portfolio_production
